In [3]:
import time
from bs4 import BeautifulSoup
from selenium import webdriver
import requests
import pandas as pd
#This tool is used for automating web-based application testing to verify that it performs expectedly.
#Beautiful Soup is a Python package for parsing HTML and XML documents (including having malformed markup, i.e. non-closed tags, so named after tag soup). It creates a parse tree for parsed pages that can be used to extract data from HTML, which is useful for web scraping.
#The requests module allows you to send HTTP requests using Python

In [4]:
driver = webdriver.Chrome()
url = 'https://www.pararius.com/apartments/amsterdam?ac=1'
response = requests.get(url)
driver.maximize_window()
driver.get(url)

time.sleep(5)
content = driver.page_source.encode('utf-8').strip()
soup = BeautifulSoup(content, "html.parser")
lists = soup.find_all('section', class_="listing-search-item")

In [5]:
title = []
location = []
price = []
area = []

In [6]:
for list in lists:

    if list.find('a', class_="listing-search-item__link listing-search-item__link--title"):
        title.append(list.find('a', class_="listing-search-item__link listing-search-item__link--title").text.replace('\n', ''))
    else:
        title.append('')

    if list.find('div', class_="listing-search-item__sub-title"):
        location.append(list.find('div', class_="listing-search-item__sub-title").text.replace('\n', ''))
    else:
        location.append('')

    if list.find('div', class_="listing-search-item__price"):
        price.append(list.find('div', class_="listing-search-item__price").text.replace('\n', ''))
    else:
        price.append('')

    if list.find('ul', class_="illustrated-features illustrated-features--compact"):
        area.append(list.find('ul', class_="illustrated-features illustrated-features--compact").text.replace('\n', ''))
    else:
        area.append('')

In [7]:
data = pd.DataFrame({'title':title, 'location':location, 'price':price, 'area':area})
pd.set_option('display.max_columns', None)
print(data)

                                                title  \
0                           Apartment Deurloostraa...
1                           Apartment Prins Hendri...
2                           Apartment Johannes Mee...
3                           Apartment Krommertstra...
4                           Apartment Krommertstra...
5                           Apartment Krommertstra...
6                           Apartment Krommertstra...
7                           Apartment Govert Flinc...
8                           Apartment Maria Austri...
9                           Apartment Apollolaan  ...
10                          Apartment De Wittenkad...
11                          Apartment Lindengracht...
12                          Apartment Bentinckstra...
13                          Apartment Govert Flinc...
14                          Apartment Frans van Mi...
15                          Apartment Da Costakade...
16                          Apartment Sanne Sannes...
17                          Apartment Bos en Lomme...
18                          Apartment Ferdinant Sp...
19                          Apartment Amstelveense...
20                          Apartment Mattenbiesst...
21                          Apartment Frieslandstr...
22                          Apartment Kinkerstraat...
23                          Apartment Het Breed   ...
24                          Apartment Von Guericke...
25                          Apartment Eerste Jan v...
26                          Apartment John Frankli...
27                          Apartment Hemonystraat...
28                          Apartment Haarlemmer H...
29                          Apartment Esmoreitstra...
30                          Apartment Tweede Jan S...
31                          Apartment Sloterkade 1...

                                             location  \
0               1078 JJ Amsterdam (Scheldebuurt)  ...
1               1011 AN Amsterdam (Nieuwmarkt/Last...
2               1063 CJ Amsterdam (Slotermeer-Noor...
3               1056 TS Amsterdam (Geuzenbuurt)   ...
4               1056 TS Amsterdam (Geuzenbuurt)   ...
5               1056 TS Amsterdam (Geuzenbuurt)   ...
6               1056 TS Amsterdam (Geuzenbuurt)   ...
7               1073 CA Amsterdam (Oude Pijp)
8               1087 JC Amsterdam (IJburg West)   ...
9               1077 AM Amsterdam (Apollobuurt)   ...
10              1052 AE Amsterdam (Staatsliedenbuu...
11                1015 KN Amsterdam (Jordaan)
12              1051 GD Amsterdam (Staatsliedenbuu...
13              1074 CJ Amsterdam (Oude Pijp)
14              1071 RW Amsterdam (Museumkwartier)...
15              1053 WT Amsterdam (Da Costabuurt) ...
16              1087 GZ Amsterdam (IJburg West)   ...
17              1055 AA Amsterdam (De Kolenkit)   ...
18              1069 KB Amsterdam (Osdorp-Midden) ...
19              1075 XS Amsterdam (Schinkelbuurt) ...
20              1087 GC Amsterdam (IJburg West)   ...
21              1082 TL Amsterdam (Buitenveldert-W...
22              1053 DD Amsterdam (Van Lennepbuurt...
23              1025 HZ Amsterdam (Buikslotermeer)...
24              1097 RC Amsterdam (Frankendael)   ...
25              1072 TR Amsterdam (Oude Pijp)
26              1056 SX Amsterdam (Van Galenbuurt)...
27              1074 BR Amsterdam (Oude Pijp)
28              1013 GM Amsterdam (Haarlemmerbuurt...
29              1055 CA Amsterdam (Erasmuspark)   ...
30              1074 CL Amsterdam (Oude Pijp)
31              1058 HM Amsterdam (Hoofddorppleinb...

                                           price  \
0                   €2,495 per month
1                   €3,250 per month
2                   €1,250 per month
3                   €1,800 per month
4                   €1,900 per month
5                   €1,950 per month
6                   €1,900 per month
7                   €1,625 per month
8                   €1,750 per month
9                   €3,000 per month
10                  €1,900 per month
11                  €1,790 per month
12                  €1,850 per month
13                  €1,750 per month
14                  €3,950 per month
15                  €2,250 per month
16                  €1,575 per month
17                  €1,450 per month
18                  €2,500 per month
19                  €2,500 per month
20                  €2,000 per month
21                  €2,300 per month
22                  €1,500 per month
23                  €1,850 per month
24                  €1,750 per month
25                  €1,650 per month
26                  €2,250 per month
27                  €3,250 per month
28                  €2,100 per month
29                  €2,450 per month
30                  €2,350 per month
31                  €2,500 per month

                                    area
0                  80 m²3 roomsFurnished
1                 117 m²3 roomsFurnished
2                      54 m²3 roomsShell
3                33 m²2 roomsUpholstered
4                36 m²2 roomsUpholstered
5                40 m²2 roomsUpholstered
6                40 m²2 roomsUpholstered
7                55 m²2 roomsUpholstered
8                       42 m²2 rooms2006
9               200 m²5 roomsUpholstered
10                 50 m²2 roomsFurnished
11                 55 m²2 roomsFurnished
12                 48 m²2 roomsFurnished
13                 48 m²2 roomsFurnished
14              195 m²6 roomsUpholstered
15                 86 m²3 roomsFurnished
16               85 m²3 roomsUpholstered
17                  31 m²1 roomFurnished
18              135 m²6 roomsUpholstered
19  75 m²3 roomsUpholstered or furnished
20              121 m²4 roomsUpholstered
21               73 m²4 roomsUpholstered
22                 30 m²2 roomsFurnished
23              100 m²4 roomsUpholstered
24                 55 m²2 roomsFurnished
25                 45 m²2 roomsFurnished
26                 98 m²4 roomsFurnished
27                 75 m²3 roomsFurnished
28                 75 m²3 roomsFurnished
29  80 m²3 roomsUpholstered or furnished
30                 60 m²3 roomsFurnished
31               95 m²3 roomsUpholstered

In [8]:

data[['area','ROOM INFO']] = data['area'].str.split('m²',expand=True)

In [9]:
print(data)

                                                title  \
0                           Apartment Deurloostraa...
1                           Apartment Prins Hendri...
2                           Apartment Johannes Mee...
3                           Apartment Krommertstra...
4                           Apartment Krommertstra...
5                           Apartment Krommertstra...
6                           Apartment Krommertstra...
7                           Apartment Govert Flinc...
8                           Apartment Maria Austri...
9                           Apartment Apollolaan  ...
10                          Apartment De Wittenkad...
11                          Apartment Lindengracht...
12                          Apartment Bentinckstra...
13                          Apartment Govert Flinc...
14                          Apartment Frans van Mi...
15                          Apartment Da Costakade...
16                          Apartment Sanne Sannes...
17                          Apartment Bos en Lomme...
18                          Apartment Ferdinant Sp...
19                          Apartment Amstelveense...
20                          Apartment Mattenbiesst...
21                          Apartment Frieslandstr...
22                          Apartment Kinkerstraat...
23                          Apartment Het Breed   ...
24                          Apartment Von Guericke...
25                          Apartment Eerste Jan v...
26                          Apartment John Frankli...
27                          Apartment Hemonystraat...
28                          Apartment Haarlemmer H...
29                          Apartment Esmoreitstra...
30                          Apartment Tweede Jan S...
31                          Apartment Sloterkade 1...

                                             location  \
0               1078 JJ Amsterdam (Scheldebuurt)  ...
1               1011 AN Amsterdam (Nieuwmarkt/Last...
2               1063 CJ Amsterdam (Slotermeer-Noor...
3               1056 TS Amsterdam (Geuzenbuurt)   ...
4               1056 TS Amsterdam (Geuzenbuurt)   ...
5               1056 TS Amsterdam (Geuzenbuurt)   ...
6               1056 TS Amsterdam (Geuzenbuurt)   ...
7               1073 CA Amsterdam (Oude Pijp)
8               1087 JC Amsterdam (IJburg West)   ...
9               1077 AM Amsterdam (Apollobuurt)   ...
10              1052 AE Amsterdam (Staatsliedenbuu...
11                1015 KN Amsterdam (Jordaan)
12              1051 GD Amsterdam (Staatsliedenbuu...
13              1074 CJ Amsterdam (Oude Pijp)
14              1071 RW Amsterdam (Museumkwartier)...
15              1053 WT Amsterdam (Da Costabuurt) ...
16              1087 GZ Amsterdam (IJburg West)   ...
17              1055 AA Amsterdam (De Kolenkit)   ...
18              1069 KB Amsterdam (Osdorp-Midden) ...
19              1075 XS Amsterdam (Schinkelbuurt) ...
20              1087 GC Amsterdam (IJburg West)   ...
21              1082 TL Amsterdam (Buitenveldert-W...
22              1053 DD Amsterdam (Van Lennepbuurt...
23              1025 HZ Amsterdam (Buikslotermeer)...
24              1097 RC Amsterdam (Frankendael)   ...
25              1072 TR Amsterdam (Oude Pijp)
26              1056 SX Amsterdam (Van Galenbuurt)...
27              1074 BR Amsterdam (Oude Pijp)
28              1013 GM Amsterdam (Haarlemmerbuurt...
29              1055 CA Amsterdam (Erasmuspark)   ...
30              1074 CL Amsterdam (Oude Pijp)
31              1058 HM Amsterdam (Hoofddorppleinb...

                                           price  area  \
0                   €2,495 per month               80
1                   €3,250 per month              117
2                   €1,250 per month               54
3                   €1,800 per month               33
4                   €1,900 per month               36
5                   €1,950 per month               40
6                   €1,900 per month               40
7                   €1,625 per month               55
8                   €1,750 per month               42
9                   €3,000 per month              200
10                  €1,900 per month               50
11                  €1,790 per month               55
12                  €1,850 per month               48
13                  €1,750 per month               48
14                  €3,950 per month              195
15                  €2,250 per month               86
16                  €1,575 per month               85
17                  €1,450 per month               31
18                  €2,500 per month              135
19                  €2,500 per month               75
20                  €2,000 per month              121
21                  €2,300 per month               73
22                  €1,500 per month               30
23                  €1,850 per month              100
24                  €1,750 per month               55
25                  €1,650 per month               45
26                  €2,250 per month               98
27                  €3,250 per month               75
28                  €2,100 per month               75
29                  €2,450 per month               80
30                  €2,350 per month               60
31                  €2,500 per month               95

                          ROOM INFO
0                  3 roomsFurnished
1                  3 roomsFurnished
2                      3 roomsShell
3                2 roomsUpholstered
4                2 roomsUpholstered
5                2 roomsUpholstered
6                2 roomsUpholstered
7                2 roomsUpholstered
8                       2 rooms2006
9                5 roomsUpholstered
10                 2 roomsFurnished
11                 2 roomsFurnished
12                 2 roomsFurnished
13                 2 roomsFurnished
14               6 roomsUpholstered
15                 3 roomsFurnished
16               3 roomsUpholstered
17                  1 roomFurnished
18               6 roomsUpholstered
19  3 roomsUpholstered or furnished
20               4 roomsUpholstered
21               4 roomsUpholstered
22                 2 roomsFurnished
23               4 roomsUpholstered
24                 2 roomsFurnished
25                 2 roomsFurnished
26                 4 roomsFurnished
27                 3 roomsFurnished
28                 3 roomsFurnished
29  3 roomsUpholstered or furnished
30                 3 roomsFurnished
31               3 roomsUpholstered

In [10]:
data[['ROOM INFO','ROOMS AVAILABLE']] = data['ROOM INFO'].str.split(' ',1,expand=True)

In [11]:
print(data)

                                                title  \
0                           Apartment Deurloostraa...
1                           Apartment Prins Hendri...
2                           Apartment Johannes Mee...
3                           Apartment Krommertstra...
4                           Apartment Krommertstra...
5                           Apartment Krommertstra...
6                           Apartment Krommertstra...
7                           Apartment Govert Flinc...
8                           Apartment Maria Austri...
9                           Apartment Apollolaan  ...
10                          Apartment De Wittenkad...
11                          Apartment Lindengracht...
12                          Apartment Bentinckstra...
13                          Apartment Govert Flinc...
14                          Apartment Frans van Mi...
15                          Apartment Da Costakade...
16                          Apartment Sanne Sannes...
17                          Apartment Bos en Lomme...
18                          Apartment Ferdinant Sp...
19                          Apartment Amstelveense...
20                          Apartment Mattenbiesst...
21                          Apartment Frieslandstr...
22                          Apartment Kinkerstraat...
23                          Apartment Het Breed   ...
24                          Apartment Von Guericke...
25                          Apartment Eerste Jan v...
26                          Apartment John Frankli...
27                          Apartment Hemonystraat...
28                          Apartment Haarlemmer H...
29                          Apartment Esmoreitstra...
30                          Apartment Tweede Jan S...
31                          Apartment Sloterkade 1...

                                             location  \
0               1078 JJ Amsterdam (Scheldebuurt)  ...
1               1011 AN Amsterdam (Nieuwmarkt/Last...
2               1063 CJ Amsterdam (Slotermeer-Noor...
3               1056 TS Amsterdam (Geuzenbuurt)   ...
4               1056 TS Amsterdam (Geuzenbuurt)   ...
5               1056 TS Amsterdam (Geuzenbuurt)   ...
6               1056 TS Amsterdam (Geuzenbuurt)   ...
7               1073 CA Amsterdam (Oude Pijp)
8               1087 JC Amsterdam (IJburg West)   ...
9               1077 AM Amsterdam (Apollobuurt)   ...
10              1052 AE Amsterdam (Staatsliedenbuu...
11                1015 KN Amsterdam (Jordaan)
12              1051 GD Amsterdam (Staatsliedenbuu...
13              1074 CJ Amsterdam (Oude Pijp)
14              1071 RW Amsterdam (Museumkwartier)...
15              1053 WT Amsterdam (Da Costabuurt) ...
16              1087 GZ Amsterdam (IJburg West)   ...
17              1055 AA Amsterdam (De Kolenkit)   ...
18              1069 KB Amsterdam (Osdorp-Midden) ...
19              1075 XS Amsterdam (Schinkelbuurt) ...
20              1087 GC Amsterdam (IJburg West)   ...
21              1082 TL Amsterdam (Buitenveldert-W...
22              1053 DD Amsterdam (Van Lennepbuurt...
23              1025 HZ Amsterdam (Buikslotermeer)...
24              1097 RC Amsterdam (Frankendael)   ...
25              1072 TR Amsterdam (Oude Pijp)
26              1056 SX Amsterdam (Van Galenbuurt)...
27              1074 BR Amsterdam (Oude Pijp)
28              1013 GM Amsterdam (Haarlemmerbuurt...
29              1055 CA Amsterdam (Erasmuspark)   ...
30              1074 CL Amsterdam (Oude Pijp)
31              1058 HM Amsterdam (Hoofddorppleinb...

                                           price  area ROOM INFO  \
0                   €2,495 per month               80          3
1                   €3,250 per month              117          3
2                   €1,250 per month               54          3
3                   €1,800 per month               33          2
4                   €1,900 per month               36          2
5                   €1,950 per month               40          2
6                   €1,900 per month               40          2
7                   €1,625 per month               55          2
8                   €1,750 per month               42          2
9                   €3,000 per month              200          5
10                  €1,900 per month               50          2
11                  €1,790 per month               55          2
12                  €1,850 per month               48          2
13                  €1,750 per month               48          2
14                  €3,950 per month              195          6
15                  €2,250 per month               86          3
16                  €1,575 per month               85          3
17                  €1,450 per month               31          1
18                  €2,500 per month              135          6
19                  €2,500 per month               75          3
20                  €2,000 per month              121          4
21                  €2,300 per month               73          4
22                  €1,500 per month               30          2
23                  €1,850 per month              100          4
24                  €1,750 per month               55          2
25                  €1,650 per month               45          2
26                  €2,250 per month               98          4
27                  €3,250 per month               75          3
28                  €2,100 per month               75          3
29                  €2,450 per month               80          3
30                  €2,350 per month               60          3
31                  €2,500 per month               95          3

                  ROOMS AVAILABLE
0                  roomsFurnished
1                  roomsFurnished
2                      roomsShell
3                roomsUpholstered
4                roomsUpholstered
5                roomsUpholstered
6                roomsUpholstered
7                roomsUpholstered
8                       rooms2006
9                roomsUpholstered
10                 roomsFurnished
11                 roomsFurnished
12                 roomsFurnished
13                 roomsFurnished
14               roomsUpholstered
15                 roomsFurnished
16               roomsUpholstered
17                  roomFurnished
18               roomsUpholstered
19  roomsUpholstered or furnished
20               roomsUpholstered
21               roomsUpholstered
22                 roomsFurnished
23               roomsUpholstered
24                 roomsFurnished
25                 roomsFurnished
26                 roomsFurnished
27                 roomsFurnished
28                 roomsFurnished
29  roomsUpholstered or furnished
30                 roomsFurnished
31               roomsUpholstered

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            32 non-null     object
 1   location         32 non-null     object
 2   price            32 non-null     object
 3   area             32 non-null     object
 4   ROOM INFO        32 non-null     object
 5   ROOMS AVAILABLE  32 non-null     object
dtypes: object(6)
memory usage: 1.6+ KB

In [13]:
data.head(5)

,title,location,price,area,ROOM INFO,ROOMS AVAILABLE
0,Apartment Deurloostraa...,1078 JJ Amsterdam (Scheldebuurt) ...,"€2,495 per month",80,3,roomsFurnished
1,Apartment Prins Hendri...,1011 AN Amsterdam (Nieuwmarkt/Last...,"€3,250 per month",117,3,roomsFurnished
2,Apartment Johannes Mee...,1063 CJ Amsterdam (Slotermeer-Noor...,"€1,250 per month",54,3,roomsShell
3,Apartment Krommertstra...,1056 TS Amsterdam (Geuzenbuurt) ...,"€1,800 per month",33,2,roomsUpholstered
4,Apartment Krommertstra...,1056 TS Amsterdam (Geuzenbuurt) ...,"€1,900 per month",36,2,roomsUpholstered

In [14]:
data.count()

title              32
location           32
price              32
area               32
ROOM INFO          32
ROOMS AVAILABLE    32
dtype: int64

In [15]:
data.isnull().sum()

title              0
location           0
price              0
area               0
ROOM INFO          0
ROOMS AVAILABLE    0
dtype: int64

In [16]:
data.isna().sum().sum()

0

In [17]:
print(data.count())
data1=data.drop_duplicates()
print(data.count())

title              32
location           32
price              32
area               32
ROOM INFO          32
ROOMS AVAILABLE    32
dtype: int64
title              32
location           32
price              32
area               32
ROOM INFO          32
ROOMS AVAILABLE    32
dtype: int64

In [18]:
data.groupby(['location','ROOM INFO']).size()

location                                                      ROOM INFO
            1011 AN Amsterdam (Nieuwmarkt/Lastage)            3            1
            1013 GM Amsterdam (Haarlemmerbuurt)               3            1
            1015 KN Amsterdam (Jordaan)                       2            1
            1025 HZ Amsterdam (Buikslotermeer)                4            1
            1051 GD Amsterdam (Staatsliedenbuurt)             2            1
            1052 AE Amsterdam (Staatsliedenbuurt)             2            1
            1053 DD Amsterdam (Van Lennepbuurt)               2            1
            1053 WT Amsterdam (Da Costabuurt)                 3            1
            1055 AA Amsterdam (De Kolenkit)                   1            1
            1055 CA Amsterdam (Erasmuspark)                   3            1
            1056 SX Amsterdam (Van Galenbuurt)                4            1
            1056 TS Amsterdam (Geuzenbuurt)                   2            4
            1058 HM Amsterdam (Hoofddorppleinbuurt)           3            1
            1063 CJ Amsterdam (Slotermeer-Noordoost)          3            1
            1069 KB Amsterdam (Osdorp-Midden)                 6            1
            1071 RW Amsterdam (Museumkwartier)                6            1
            1072 TR Amsterdam (Oude Pijp)                     2            1
            1073 CA Amsterdam (Oude Pijp)                     2            1
            1074 BR Amsterdam (Oude Pijp)                     3            1
            1074 CJ Amsterdam (Oude Pijp)                     2            1
            1074 CL Amsterdam (Oude Pijp)                     3            1
            1075 XS Amsterdam (Schinkelbuurt)                 3            1
            1077 AM Amsterdam (Apollobuurt)                   5            1
            1078 JJ Amsterdam (Scheldebuurt)                  3            1
            1082 TL Amsterdam (Buitenveldert-West)            4            1
            1087 GC Amsterdam (IJburg West)                   4            1
            1087 GZ Amsterdam (IJburg West)                   3            1
            1087 JC Amsterdam (IJburg West)                   2            1
            1097 RC Amsterdam (Frankendael)                   2            1
dtype: int64

In [19]:
data.groupby(['price','ROOM INFO']).size()

price                                         ROOM INFO
                €1,250 per month              3            1
                €1,450 per month              1            1
                €1,500 per month              2            1
                €1,575 per month              3            1
                €1,625 per month              2            1
                €1,650 per month              2            1
                €1,750 per month              2            3
                €1,790 per month              2            1
                €1,800 per month              2            1
                €1,850 per month              2            1
                                              4            1
                €1,900 per month              2            3
                €1,950 per month              2            1
                €2,000 per month              4            1
                €2,100 per month              3            1
                €2,250 per month              3            1
                                              4            1
                €2,300 per month              4            1
                €2,350 per month              3            1
                €2,450 per month              3            1
                €2,495 per month              3            1
                €2,500 per month              3            2
                                              6            1
                €3,000 per month              5            1
                €3,250 per month              3            2
                €3,950 per month              6            1
dtype: int64

In [20]:
#To add IP in mongoDB
import socket
hostname = socket.gethostname()
IP = socket.gethostbyname(hostname)
print(IP)
print(hostname)

192.168.1.45
DESKTOP-MFP1R0R

In [21]:
!pip install pymongo

Requirement already satisfied: pymongo in c:\users\dell\anaconda3\lib\site-packages (4.3.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\users\dell\anaconda3\lib\site-packages (from pymongo) (2.2.1)

In [22]:
import pymongo
client = pymongo.MongoClient("mongodb+srv://RamDbs:RamDbs123@cluster0.diqp9ef.mongodb.net/?retryWrites=true&w=majority")

In [23]:
df =data.to_dict(orient = "records")

In [24]:
df

[{'title': '                        Apartment Deurloostraat                            ',
  'location': '            1078 JJ Amsterdam (Scheldebuurt)        ',
  'price': '                €2,495 per month            ',
  'area': '80 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Prins Hendrikkade                            ',
  'location': '            1011 AN Amsterdam (Nieuwmarkt/Lastage)        ',
  'price': '                €3,250 per month            ',
  'area': '117 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Johannes Meewisstraat                            ',
  'location': '            1063 CJ Amsterdam (Slotermeer-Noordoost)        ',
  'price': '                €1,250 per month            ',
  'area': '54 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsShell'},
 {'title': '                        Apartment Krommertstraat                            ',
  'location': '            1056 TS Amsterdam (Geuzenbuurt)        ',
  'price': '                €1,800 per month            ',
  'area': '33 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Krommertstraat                            ',
  'location': '            1056 TS Amsterdam (Geuzenbuurt)        ',
  'price': '                €1,900 per month            ',
  'area': '36 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Krommertstraat                            ',
  'location': '            1056 TS Amsterdam (Geuzenbuurt)        ',
  'price': '                €1,950 per month            ',
  'area': '40 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Krommertstraat                            ',
  'location': '            1056 TS Amsterdam (Geuzenbuurt)        ',
  'price': '                €1,900 per month            ',
  'area': '40 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Govert Flinckstraat                            ',
  'location': '            1073 CA Amsterdam (Oude Pijp)        ',
  'price': '                €1,625 per month            ',
  'area': '55 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Maria Austriastraat                            ',
  'location': '            1087 JC Amsterdam (IJburg West)        ',
  'price': '                €1,750 per month            ',
  'area': '42 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'rooms2006'},
 {'title': '                        Apartment Apollolaan                            ',
  'location': '            1077 AM Amsterdam (Apollobuurt)        ',
  'price': '                €3,000 per month            ',
  'area': '200 ',
  'ROOM INFO': '5',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment De Wittenkade 91 1                            ',
  'location': '            1052 AE Amsterdam (Staatsliedenbuurt)        ',
  'price': '                €1,900 per month            ',
  'area': '50 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Lindengracht 254 H                            ',
  'location': '            1015 KN Amsterdam (Jordaan)        ',
  'price': '                €1,790 per month            ',
  'area': '55 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Bentinckstraat                            ',
  'location': '            1051 GD Amsterdam (Staatsliedenbuurt)        ',
  'price': '                €1,850 per month            ',
  'area': '48 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Govert Flinckstraat                            ',
  'location': '            1074 CJ Amsterdam (Oude Pijp)        ',
  'price': '                €1,750 per month            ',
  'area': '48 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Frans van Mierisstraat                            ',
  'location': '            1071 RW Amsterdam (Museumkwartier)        ',
  'price': '                €3,950 per month            ',
  'area': '195 ',
  'ROOM INFO': '6',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Da Costakade 143 C                            ',
  'location': '            1053 WT Amsterdam (Da Costabuurt)        ',
  'price': '                €2,250 per month            ',
  'area': '86 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Sanne Sanneshof 6                            ',
  'location': '            1087 GZ Amsterdam (IJburg West)        ',
  'price': '                €1,575 per month            ',
  'area': '85 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Bos en Lommerplantsoen 25 K                            ',
  'location': '            1055 AA Amsterdam (De Kolenkit)        ',
  'price': '                €1,450 per month            ',
  'area': '31 ',
  'ROOM INFO': '1',
  'ROOMS AVAILABLE': 'roomFurnished'},
 {'title': '                        Apartment Ferdinant Spitstraat 79                            ',
  'location': '            1069 KB Amsterdam (Osdorp-Midden)        ',
  'price': '                €2,500 per month            ',
  'area': '135 ',
  'ROOM INFO': '6',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Amstelveenseweg 200 2                            ',
  'location': '            1075 XS Amsterdam (Schinkelbuurt)        ',
  'price': '                €2,500 per month            ',
  'area': '75 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsUpholstered or furnished'},
 {'title': '                        Apartment Mattenbiesstraat 155                            ',
  'location': '            1087 GC Amsterdam (IJburg West)        ',
  'price': '                €2,000 per month            ',
  'area': '121 ',
  'ROOM INFO': '4',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Frieslandstraat                            ',
  'location': '            1082 TL Amsterdam (Buitenveldert-West)        ',
  'price': '                €2,300 per month            ',
  'area': '73 ',
  'ROOM INFO': '4',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Kinkerstraat                            ',
  'location': '            1053 DD Amsterdam (Van Lennepbuurt)        ',
  'price': '                €1,500 per month            ',
  'area': '30 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Het Breed                            ',
  'location': '            1025 HZ Amsterdam (Buikslotermeer)        ',
  'price': '                €1,850 per month            ',
  'area': '100 ',
  'ROOM INFO': '4',
  'ROOMS AVAILABLE': 'roomsUpholstered'},
 {'title': '                        Apartment Von Guerickestraat                            ',
  'location': '            1097 RC Amsterdam (Frankendael)        ',
  'price': '                €1,750 per month            ',
  'area': '55 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Eerste Jan van der Heijdenstraat                            ',
  'location': '            1072 TR Amsterdam (Oude Pijp)        ',
  'price': '                €1,650 per month            ',
  'area': '45 ',
  'ROOM INFO': '2',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment John Franklinstraat 47 1                            ',
  'location': '            1056 SX Amsterdam (Van Galenbuurt)        ',
  'price': '                €2,250 per month            ',
  'area': '98 ',
  'ROOM INFO': '4',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Hemonystraat 26 C                            ',
  'location': '            1074 BR Amsterdam (Oude Pijp)        ',
  'price': '                €3,250 per month            ',
  'area': '75 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Haarlemmer Houttuinen                            ',
  'location': '            1013 GM Amsterdam (Haarlemmerbuurt)        ',
  'price': '                €2,100 per month            ',
  'area': '75 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Esmoreitstraat 25 HS                            ',
  'location': '            1055 CA Amsterdam (Erasmuspark)        ',
  'price': '                €2,450 per month            ',
  'area': '80 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsUpholstered or furnished'},
 {'title': '                        Apartment Tweede Jan Steenstraat                            ',
  'location': '            1074 CL Amsterdam (Oude Pijp)        ',
  'price': '                €2,350 per month            ',
  'area': '60 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsFurnished'},
 {'title': '                        Apartment Sloterkade 134 G                            ',
  'location': '            1058 HM Amsterdam (Hoofddorppleinbuurt)        ',
  'price': '                €2,500 per month            ',
  'area': '95 ',
  'ROOM INFO': '3',
  'ROOMS AVAILABLE': 'roomsUpholstered'}]

In [25]:
#Database name isApartments
database =client["Apartments"]

In [26]:
print(database)

Database(MongoClient(host=['ac-wnookl7-shard-00-01.diqp9ef.mongodb.net:27017', 'ac-wnookl7-shard-00-02.diqp9ef.mongodb.net:27017', 'ac-wnookl7-shard-00-00.diqp9ef.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-dpdx61-shard-0', tls=True), 'Apartments')

In [27]:
database.AmsterdamApartments.insert_many(df)